#!/bin/bash

declare -A commands=(
  ['build-docker']=build-docker
  ['run-docker']=run-docker
  ['stop-docker']=stop-docker
);

selectedCMD=$1

if [[ $# -gt 0 && ${commands[$selectedCMD]} ]]; then
    shift
    if [[ ${commands[$selectedCMD]} ]]; then

      if [[ $selectedCMD == 'build-docker' ]]; then
        docker build -f docker/dockerfile -t my-nestjs:latest . --progress=plain --network=host
      fi

      if [[ $selectedCMD == 'run-docker' ]]; then
        docker-compose -f docker/docker-compose.yml up -d
      fi

      if [[ $selectedCMD == 'stop-docker' ]]; then
        docker-compose -f docker/docker-compose.yml down
      fi

    else
      echo ""
      echo "unknown commands"
      echo "try one of these -> ${commands[@]}"
      echo ""
    fi
    
else
  echo ""
  echo "unknown command"
  echo "try one of these -> ${commands[@]}"
  echo "example: ./run ${commands[build-docker]} "
  echo ""

fi

