# version: '3.7'
x-nestjs: &nestjs
  # this how to set .env file path in docker composer file
  # env_file:
  #     - ../.env
  image: my-nestjs:latest
  container_name: nestjs-app
  working_dir: /app
  restart: unless-stopped
  volumes:
    - ../.env:/app/.env:ro
    - ../logs:/app/logs:delegated

    # it seems like using image : node:alpine cant read HOST variable , that's why below line is required 
    # 172.17.0.1 =  default IP HOST of docker
  extra_hosts:
    - "HOST_IP_ANOTHER:172.17.0.1"
    - "HOST_IP:host-gateway"
  healthcheck:
      test: ["CMD", "node", "--version"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: 10


services:
  nestjs-app:
    <<: [*nestjs, *logging]
    container_name: nestjs-app
    working_dir: /app
    environment:
      - IS_FORWARD_LOG_TO_FILE=true
    ports:
      - "${PORT:-3000}:3000"
    expose:
      - '3000'
    command: npm run start:prod
    profiles:
      - production
      - migration
    healthcheck:
      test: ["CMD", "pgrep", "-f", "run start:prod"]

  nestjs-app-migrations:
    <<: [*nestjs, *logging]
    container_name: nestjs-app-migrations
    restart: no
    command: npm run prisma migrate deploy
    profiles: ["migration"]
    depends_on:
      - nestjs-app